import csv
import os

# Extracted rooms per image
# Format: List of dicts with keys: 'Image', 'Floor', 'House Name', 'Rooms'
# 'Rooms': List of dicts with 'Room Number', 'Room Type'
rooms_data = [
    {
        'Image': '001_Max_P_Graham_Floor_3_pdf_house_0.png',
        'Floor': 3,
        'House Name': 'Graham',
        'Rooms': [
            {'Room Number': 'C311A', 'Room Type': 'Single'},
            {'Room Number': 'C309B', 'Room Type': 'Double'},
            {'Room Number': 'C309A', 'Room Type': 'Double'},
            {'Room Number': 'C307B', 'Room Type': 'Double'},
            {'Room Number': 'C307A', 'Room Type': 'Double'},
            {'Room Number': 'C305B', 'Room Type': 'Double'},
            {'Room Number': 'C305A', 'Room Type': 'Double'},
            {'Room Number': 'C303B', 'Room Type': 'Double'},
            {'Room Number': 'C303A', 'Room Type': 'Double'},
            {'Room Number': 'C301B', 'Room Type': 'Double'},
            {'Room Number': 'C301A', 'Room Type': 'Double'},
            {'Room Number': 'C316A', 'Room Type': 'Single'},
            {'Room Number': 'C316B', 'Room Type': 'Single'},
            {'Room Number': 'C314A', 'Room Type': 'Single'},
            {'Room Number': 'C314B', 'Room Type': 'Single'},
            {'Room Number': 'C312A', 'Room Type': 'Double'},
            {'Room Number': 'C312B', 'Room Type': 'Double'},
            {'Room Number': 'C310A', 'Room Type': 'Double'},
            {'Room Number': 'C310B', 'Room Type': 'Double'},
            {'Room Number': 'C308A', 'Room Type': 'Double'},
            {'Room Number': 'C308B', 'Room Type': 'Double'},
            {'Room Number': 'C306A', 'Room Type': 'Double'},
            {'Room Number': 'C306B', 'Room Type': 'Double'},
            {'Room Number': 'C304A', 'Room Type': 'Double'},
            {'Room Number': 'C304B', 'Room Type': 'Double'},
        ]
    },
    {
        'Image': '002_Max_P_Alper_Floor_3_pdf_house_0.png',
        'Floor': 3,
        'House Name': 'Alper',
        'Rooms': [
            {'Room Number': 'E301A', 'Room Type': 'Double'},
            {'Room Number': 'E301B', 'Room Type': 'Double'},
            {'Room Number': 'E303A', 'Room Type': 'Double'},
            {'Room Number': 'E303B', 'Room Type': 'Double'},
            {'Room Number': 'E305A', 'Room Type': 'Double'},
            {'Room Number': 'E305B', 'Room Type': 'Double'},
            {'Room Number': 'E307A', 'Room Type': 'Double'},
            {'Room Number': 'E307B', 'Room Type': 'Double'},
            {'Room Number': 'E309A', 'Room Type': 'Single'},
            {'Room Number': 'E302B', 'Room Type': 'Single'},
            {'Room Number': 'E302A', 'Room Type': 'Single'},
            {'Room Number': 'E304B', 'Room Type': 'Single'},
            {'Room Number': 'E304A', 'Room Type': 'Single'},
            {'Room Number': 'E306B', 'Room Type': 'Double'},
            {'Room Number': 'E306A', 'Room Type': 'Double'},
            {'Room Number': 'E308B', 'Room Type': 'Double'},
            {'Room Number': 'E308A', 'Room Type': 'Double'},
            {'Room Number': 'E310B', 'Room Type': 'Single'},
            {'Room Number': 'E310A', 'Room Type': 'Single'},
            {'Room Number': 'E311A', 'Room Type': 'Single'},
            {'Room Number': 'E311B', 'Room Type': 'Single'},
            {'Room Number': 'E313A', 'Room Type': 'Double'},
            {'Room Number': 'E313B', 'Room Type': 'Double'},
            {'Room Number': 'E315A', 'Room Type': 'Double'},
            {'Room Number': 'E315B', 'Room Type': 'Double'},
            {'Room Number': 'E317A', 'Room Type': 'Double'},
            {'Room Number': 'E317B', 'Room Type': 'Double'},
            {'Room Number': 'E319A', 'Room Type': 'Double'},
            {'Room Number': 'E319B', 'Room Type': 'Double'},
            {'Room Number': 'E321A', 'Room Type': 'Double'},
            {'Room Number': 'E321B', 'Room Type': 'Double'},
            {'Room Number': 'E323A', 'Room Type': 'Single'},
            {'Room Number': 'E323B', 'Room Type': 'Single'},
            {'Room Number': 'E312B', 'Room Type': 'Single'},
            {'Room Number': 'E312A', 'Room Type': 'Single'},
            {'Room Number': 'E314B', 'Room Type': 'Double'},
            {'Room Number': 'E314A', 'Room Type': 'Double'},
            {'Room Number': 'E320B', 'Room Type': 'Single'},
            {'Room Number': 'E320A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '003_Max_P_Alper_Floor_4_pdf_house_0.png',
        'Floor': 4,
        'House Name': 'Alper',
        'Rooms': [
            {'Room Number': 'E411A', 'Room Type': 'Single'},
            {'Room Number': 'E411B', 'Room Type': 'Single'},
            {'Room Number': 'E413A', 'Room Type': 'Double'},
            {'Room Number': 'E413B', 'Room Type': 'Double'},
            {'Room Number': 'E415A', 'Room Type': 'Double'},
            {'Room Number': 'E415B', 'Room Type': 'Double'},
            {'Room Number': 'E417A', 'Room Type': 'Double'},
            {'Room Number': 'E417B', 'Room Type': 'Double'},
            {'Room Number': 'E419A', 'Room Type': 'Double'},
            {'Room Number': 'E419B', 'Room Type': 'Double'},
            {'Room Number': 'E421A', 'Room Type': 'Double'},
            {'Room Number': 'E421B', 'Room Type': 'Double'},
            {'Room Number': 'E423A', 'Room Type': 'Single'},
            {'Room Number': 'E423B', 'Room Type': 'Single'},
            {'Room Number': 'E412A', 'Room Type': 'Single'},
            {'Room Number': 'E414A', 'Room Type': 'Double'},
            {'Room Number': 'E414B', 'Room Type': 'Double'},
            {'Room Number': 'E416B', 'Room Type': 'Double'},
            {'Room Number': 'E416A', 'Room Type': 'Double'},
            {'Room Number': 'E418B', 'Room Type': 'Double'},
            {'Room Number': 'E418A', 'Room Type': 'Double'},
            {'Room Number': 'E420B', 'Room Type': 'Single'},
            {'Room Number': 'E420A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '004_Max_P_Graham_Floor_4_pdf_house_0.png',
        'Floor': 4,
        'House Name': 'Graham',
        'Rooms': [
            {'Room Number': 'C411A', 'Room Type': 'Single'},
            {'Room Number': 'C409B', 'Room Type': 'Double'},
            {'Room Number': 'C409A', 'Room Type': 'Double'},
            {'Room Number': 'C407B', 'Room Type': 'Double'},
            {'Room Number': 'C407A', 'Room Type': 'Double'},
            {'Room Number': 'C405B', 'Room Type': 'Double'},
            {'Room Number': 'C405A', 'Room Type': 'Double'},
            {'Room Number': 'C416A', 'Room Type': 'Single'},
            {'Room Number': 'C416B', 'Room Type': 'Single'},
            {'Room Number': 'C414A', 'Room Type': 'Single'},
            {'Room Number': 'C414B', 'Room Type': 'Single'},
            {'Room Number': 'C412A', 'Room Type': 'Double'},
            {'Room Number': 'C412B', 'Room Type': 'Double'},
            {'Room Number': 'C410A', 'Room Type': 'Double'},
            {'Room Number': 'C410B', 'Room Type': 'Double'},
            {'Room Number': 'C408A', 'Room Type': 'Double'},
            {'Room Number': 'C408B', 'Room Type': 'Double'},
            {'Room Number': 'C406A', 'Room Type': 'Double'},
            {'Room Number': 'C406B', 'Room Type': 'Double'},
            {'Room Number': 'C404A', 'Room Type': 'Double'},
            {'Room Number': 'C404B', 'Room Type': 'Double'},
        ]
    },
    {
        'Image': '005_Max_P_Woodward_Floor_4_pdf_house_0.png',
        'Floor': 4,
        'House Name': 'Woodward',
        'Rooms': [
            {'Room Number': 'C421B', 'Room Type': 'Double'},
            {'Room Number': 'C421A', 'Room Type': 'Double'},
            {'Room Number': 'C423B', 'Room Type': 'Double'},
            {'Room Number': 'C423A', 'Room Type': 'Double'},
            {'Room Number': 'C425B', 'Room Type': 'Double'},
            {'Room Number': 'C425A', 'Room Type': 'Double'},
            {'Room Number': 'C427B', 'Room Type': 'Single'},
            {'Room Number': 'C427A', 'Room Type': 'Single'},
            {'Room Number': 'C429B', 'Room Type': 'Single'},
            {'Room Number': 'C429A', 'Room Type': 'Single'},
            {'Room Number': 'C422A', 'Room Type': 'Double'},
            {'Room Number': 'C422B', 'Room Type': 'Double'},
            {'Room Number': 'C424A', 'Room Type': 'Double'},
            {'Room Number': 'C424B', 'Room Type': 'Double'},
            {'Room Number': 'C426A', 'Room Type': 'Double'},
            {'Room Number': 'C426B', 'Room Type': 'Double'},
            {'Room Number': 'C428B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '006_Max_P_Woodward_Floor_3_pdf_house_0.png',
        'Floor': 3,
        'House Name': 'Woodward',
        'Rooms': [
            {'Room Number': 'C325B', 'Room Type': 'Double'},
            {'Room Number': 'C325A', 'Room Type': 'Double'},
            {'Room Number': 'C327B', 'Room Type': 'Single'},
            {'Room Number': 'C327A', 'Room Type': 'Single'},
            {'Room Number': 'C329B', 'Room Type': 'Single'},
            {'Room Number': 'C329A', 'Room Type': 'Single'},
            {'Room Number': 'C322A', 'Room Type': 'Double'},
            {'Room Number': 'C322B', 'Room Type': 'Double'},
            {'Room Number': 'C324A', 'Room Type': 'Double'},
            {'Room Number': 'C324B', 'Room Type': 'Double'},
            {'Room Number': 'C326A', 'Room Type': 'Double'},
            {'Room Number': 'C326B', 'Room Type': 'Double'},
            {'Room Number': 'C328A', 'Room Type': 'Single'},
            {'Room Number': 'C328B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '007_Max_P_Flint_Floor_1_pdf_house_0.png',
        'Floor': 1,
        'House Name': 'Flint',
        'Rooms': [
            {'Room Number': 'C111A', 'Room Type': 'Single'},
            {'Room Number': 'C109B', 'Room Type': 'Double'},
            {'Room Number': 'C109A', 'Room Type': 'Double'},
            {'Room Number': 'C107B', 'Room Type': 'Double'},
            {'Room Number': 'C107A', 'Room Type': 'Double'},
            {'Room Number': 'C105B', 'Room Type': 'Double'},
            {'Room Number': 'C105A', 'Room Type': 'Double'},
            {'Room Number': 'C103B', 'Room Type': 'Double'},
            {'Room Number': 'C103A', 'Room Type': 'Double'},
            {'Room Number': 'C101B', 'Room Type': 'Double'},
            {'Room Number': 'C101A', 'Room Type': 'Double'},
            {'Room Number': 'C116A', 'Room Type': 'Single'},
            {'Room Number': 'C116B', 'Room Type': 'Single'},
            {'Room Number': 'C114A', 'Room Type': 'Single'},
            {'Room Number': 'C114B', 'Room Type': 'Single'},
            {'Room Number': 'C112A', 'Room Type': 'Double'},
            {'Room Number': 'C112B', 'Room Type': 'Double'},
            {'Room Number': 'C110A', 'Room Type': 'Double'},
            {'Room Number': 'C110B', 'Room Type': 'Double'},
            {'Room Number': 'C108A', 'Room Type': 'Double'},
            {'Room Number': 'C108B', 'Room Type': 'Double'},
            {'Room Number': 'C106A', 'Room Type': 'Double'},
            {'Room Number': 'C106B', 'Room Type': 'Double'},
        ]
    },
    {
        'Image': '008_Max_P_Flint_Floor_2_pdf_house_0.png',
        'Floor': 2,
        'House Name': 'Flint',
        'Rooms': [
            {'Room Number': 'C211A', 'Room Type': 'Single'},
            {'Room Number': 'C209B', 'Room Type': 'Double'},
            {'Room Number': 'C209A', 'Room Type': 'Double'},
            {'Room Number': 'C207B', 'Room Type': 'Double'},
            {'Room Number': 'C207A', 'Room Type': 'Double'},
            {'Room Number': 'C205B', 'Room Type': 'Double'},
            {'Room Number': 'C205A', 'Room Type': 'Double'},
            {'Room Number': 'C216A', 'Room Type': 'Single'},
            {'Room Number': 'C216B', 'Room Type': 'Single'},
            {'Room Number': 'C214A', 'Room Type': 'Single'},
            {'Room Number': 'C214B', 'Room Type': 'Single'},
            {'Room Number': 'C212A', 'Room Type': 'Double'},
            {'Room Number': 'C212B', 'Room Type': 'Double'},
            {'Room Number': 'C210A', 'Room Type': 'Double'},
            {'Room Number': 'C210B', 'Room Type': 'Double'},
            {'Room Number': 'C208A', 'Room Type': 'Double'},
            {'Room Number': 'C208B', 'Room Type': 'Double'},
            {'Room Number': 'C206A', 'Room Type': 'Double'},
            {'Room Number': 'C206B', 'Room Type': 'Double'},
            {'Room Number': 'C204A', 'Room Type': 'Double'},
            {'Room Number': 'C204B', 'Room Type': 'Double'},
        ]
    },
    {
        'Image': '009_Max_P_Rickert_Floor_3_pdf_house_0.png',
        'Floor': 3,
        'House Name': 'Rickert',
        'Rooms': [
            {'Room Number': 'W310A', 'Room Type': 'Single'},
            {'Room Number': 'W310B', 'Room Type': 'Single'},
            {'Room Number': 'W308A', 'Room Type': 'Double'},
            {'Room Number': 'W308B', 'Room Type': 'Double'},
            {'Room Number': 'W306A', 'Room Type': 'Double'},
            {'Room Number': 'W306B', 'Room Type': 'Double'},
            {'Room Number': 'W304A', 'Room Type': 'Double'},
            {'Room Number': 'W304B', 'Room Type': 'Double'},
            {'Room Number': 'W302A', 'Room Type': 'Single'},
            {'Room Number': 'W302B', 'Room Type': 'Single'},
            {'Room Number': 'W305A', 'Room Type': 'Single'},
            {'Room Number': 'W303B', 'Room Type': 'Double'},
            {'Room Number': 'W303A', 'Room Type': 'Double'},
            {'Room Number': 'W301B', 'Room Type': 'Double'},
            {'Room Number': 'W301A', 'Room Type': 'Double'},
            {'Room Number': 'W314B', 'Room Type': 'Single'},
            {'Room Number': 'W314A', 'Room Type': 'Single'},
            {'Room Number': 'W311A', 'Room Type': 'Double'},
            {'Room Number': 'W311B', 'Room Type': 'Double'},
            {'Room Number': 'W313A', 'Room Type': 'Single'},
            {'Room Number': 'W313B', 'Room Type': 'Single'},
            {'Room Number': 'W320B', 'Room Type': 'Single'},
            {'Room Number': 'W320A', 'Room Type': 'Single'},
            {'Room Number': 'W322B', 'Room Type': 'Single'},
            {'Room Number': 'W322A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '010_Max_P_Rickert_Floor_4_pdf_house_0.png',
        'Floor': 4,
        'House Name': 'Rickert',
        'Rooms': [
            {'Room Number': 'W410A', 'Room Type': 'Single'},
            {'Room Number': 'W410B', 'Room Type': 'Single'},
            {'Room Number': 'W408A', 'Room Type': 'Double'},
            {'Room Number': 'W408B', 'Room Type': 'Double'},
            {'Room Number': 'W406A', 'Room Type': 'Double'},
            {'Room Number': 'W406B', 'Room Type': 'Double'},
            {'Room Number': 'W404A', 'Room Type': 'Double'},
            {'Room Number': 'W404B', 'Room Type': 'Double'},
            {'Room Number': 'W402A', 'Room Type': 'Single'},
            {'Room Number': 'W402B', 'Room Type': 'Single'},
            {'Room Number': 'W405B', 'Room Type': 'Single'},
            {'Room Number': 'W405A', 'Room Type': 'Single'},
            {'Room Number': 'W403B', 'Room Type': 'Double'},
            {'Room Number': 'W403A', 'Room Type': 'Double'},
            {'Room Number': 'W401B', 'Room Type': 'Double'},
            {'Room Number': 'W401A', 'Room Type': 'Double'},
            {'Room Number': 'W414A', 'Room Type': 'Single'},
            {'Room Number': 'W416B', 'Room Type': 'Double'},
            {'Room Number': 'W416A', 'Room Type': 'Double'},
            {'Room Number': 'W418B', 'Room Type': 'Double'},
            {'Room Number': 'W418A', 'Room Type': 'Double'},
            {'Room Number': 'W420B', 'Room Type': 'Single'},
            {'Room Number': 'W420A', 'Room Type': 'Single'},
            {'Room Number': 'W422B', 'Room Type': 'Single'},
            {'Room Number': 'W422A', 'Room Type': 'Single'},
            {'Room Number': 'W411A', 'Room Type': 'Double'},
            {'Room Number': 'W411B', 'Room Type': 'Double'},
            {'Room Number': 'W413A', 'Room Type': 'Single'},
            {'Room Number': 'W413B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '011_Max_P_Wallace_Floor_1_pdf_house_0.png',
        'Floor': 1,
        'House Name': 'Wallace',
        'Rooms': [
            {'Room Number': 'W114A', 'Room Type': 'Single'},
            {'Room Number': 'W116B', 'Room Type': 'Double'},
            {'Room Number': 'W116A', 'Room Type': 'Double'},
            {'Room Number': 'W118B', 'Room Type': 'Double'},
            {'Room Number': 'W118A', 'Room Type': 'Double'},
            {'Room Number': 'W120B', 'Room Type': 'Single'},
            {'Room Number': 'W120A', 'Room Type': 'Single'},
            {'Room Number': 'W122B', 'Room Type': 'Single'},
            {'Room Number': 'W122A', 'Room Type': 'Single'},
            {'Room Number': 'W110A', 'Room Type': 'Single'},
            {'Room Number': 'W110B', 'Room Type': 'Single'},
            {'Room Number': 'W108A', 'Room Type': 'Double'},
            {'Room Number': 'W108B', 'Room Type': 'Double'},
            {'Room Number': 'W106A', 'Room Type': 'Double'},
            {'Room Number': 'W106B', 'Room Type': 'Double'},
            {'Room Number': 'W104A', 'Room Type': 'Double'},
            {'Room Number': 'W104B', 'Room Type': 'Double'},
            {'Room Number': 'W102A', 'Room Type': 'Single'},
            {'Room Number': 'W102B', 'Room Type': 'Single'},
            {'Room Number': 'W111A', 'Room Type': 'Double'},
            {'Room Number': 'W111B', 'Room Type': 'Double'},
            {'Room Number': 'W113A', 'Room Type': 'Single'},
            {'Room Number': 'W113B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '012_Max_P_Wallace_Floor_2_pdf_house_0.png',
        'Floor': 2,
        'House Name': 'Wallace',
        'Rooms': [
            {'Room Number': 'W214B', 'Room Type': 'Single'},
            {'Room Number': 'W214A', 'Room Type': 'Single'},
            {'Room Number': 'W220B', 'Room Type': 'Single'},
            {'Room Number': 'W220A', 'Room Type': 'Single'},
            {'Room Number': 'W222B', 'Room Type': 'Single'},
            {'Room Number': 'W222A', 'Room Type': 'Single'},
            {'Room Number': 'W210A', 'Room Type': 'Single'},
            {'Room Number': 'W210B', 'Room Type': 'Single'},
            {'Room Number': 'W208A', 'Room Type': 'Double'},
            {'Room Number': 'W208B', 'Room Type': 'Double'},
            {'Room Number': 'W206A', 'Room Type': 'Double'},
            {'Room Number': 'W206B', 'Room Type': 'Double'},
            {'Room Number': 'W204A', 'Room Type': 'Double'},
            {'Room Number': 'W204B', 'Room Type': 'Double'},
            {'Room Number': 'W202A', 'Room Type': 'Single'},
            {'Room Number': 'W211A', 'Room Type': 'Double'},
            {'Room Number': 'W211B', 'Room Type': 'Double'},
            {'Room Number': 'W213A', 'Room Type': 'Single'},
            {'Room Number': 'W213B', 'Room Type': 'Single'},
            {'Room Number': 'W205B', 'Room Type': 'Single'},
            {'Room Number': 'W205A', 'Room Type': 'Single'},
            {'Room Number': 'W203B', 'Room Type': 'Double'},
            {'Room Number': 'W203A', 'Room Type': 'Double'},
            {'Room Number': 'W201B', 'Room Type': 'Double'},
            {'Room Number': 'W201A', 'Room Type': 'Double'},
        ]
    },
    {
        'Image': '013_Max_P_Woodward_Floor_2_pdf_house_0.png',
        'Floor': 2,
        'House Name': 'Woodward',
        'Rooms': [
            {'Room Number': 'C221B', 'Room Type': 'Double'},
            {'Room Number': 'C221A', 'Room Type': 'Double'},
            {'Room Number': 'C223B', 'Room Type': 'Double'},
            {'Room Number': 'C223A', 'Room Type': 'Double'},
            {'Room Number': 'C225B', 'Room Type': 'Double'},
            {'Room Number': 'C225A', 'Room Type': 'Double'},
            {'Room Number': 'C227B', 'Room Type': 'Single'},
            {'Room Number': 'C227A', 'Room Type': 'Single'},
            {'Room Number': 'C229B', 'Room Type': 'Single'},
            {'Room Number': 'C229A', 'Room Type': 'Single'},
            {'Room Number': 'C222A', 'Room Type': 'Double'},
            {'Room Number': 'C222B', 'Room Type': 'Double'},
            {'Room Number': 'C224A', 'Room Type': 'Double'},
            {'Room Number': 'C224B', 'Room Type': 'Double'},
            {'Room Number': 'C226A', 'Room Type': 'Double'},
            {'Room Number': 'C226B', 'Room Type': 'Double'},
            {'Room Number': 'C228A', 'Room Type': 'Single'},
            {'Room Number': 'C228B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '014_Max_P_Woodward_Floor_1_pdf_house_0.png',
        'Floor': 1,
        'House Name': 'Woodward',
        'Rooms': [
            {'Room Number': 'C123B', 'Room Type': 'Double'},
            {'Room Number': 'C123A', 'Room Type': 'Double'},
            {'Room Number': 'C125B', 'Room Type': 'Double'},
            {'Room Number': 'C125A', 'Room Type': 'Double'},
            {'Room Number': 'C127B', 'Room Type': 'Single'},
            {'Room Number': 'C127A', 'Room Type': 'Single'},
            {'Room Number': 'C129B', 'Room Type': 'Single'},
            {'Room Number': 'C129A', 'Room Type': 'Single'},
            {'Room Number': 'C124A', 'Room Type': 'Double'},
            {'Room Number': 'C124B', 'Room Type': 'Double'},
            {'Room Number': 'C126A', 'Room Type': 'Double'},
            {'Room Number': 'C126B', 'Room Type': 'Double'},
            {'Room Number': 'C128B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '015_Max_P_Hoover_Floor_3_pdf_house_0.png',
        'Floor': 3,
        'House Name': 'Hoover',
        'Rooms': [
            {'Room Number': 'E337B', 'Room Type': 'Single'},
            {'Room Number': 'E337A', 'Room Type': 'Single'},
            {'Room Number': 'E335B', 'Room Type': 'Double'},
            {'Room Number': 'E335A', 'Room Type': 'Double'},
            {'Room Number': 'E333B', 'Room Type': 'Double'},
            {'Room Number': 'E333A', 'Room Type': 'Double'},
            {'Room Number': 'E331B', 'Room Type': 'Double'},
            {'Room Number': 'E331A', 'Room Type': 'Double'},
            {'Room Number': 'E329B', 'Room Type': 'Double'},
            {'Room Number': 'E329A', 'Room Type': 'Double'},
            {'Room Number': 'E327B', 'Room Type': 'Single'},
            {'Room Number': 'E327A', 'Room Type': 'Single'},
            {'Room Number': 'E328A', 'Room Type': 'Single'},
            {'Room Number': 'E328B', 'Room Type': 'Single'},
            {'Room Number': 'E326A', 'Room Type': 'Double'},
            {'Room Number': 'E326B', 'Room Type': 'Double'},
            {'Room Number': 'E324A', 'Room Type': 'Double'},
            {'Room Number': 'E324B', 'Room Type': 'Double'},
            {'Room Number': 'E322A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '016_Max_P_May_Floor_1_pdf_house_0.png',
        'Floor': 1,
        'House Name': 'May',
        'Rooms': [
            {'Room Number': 'E120A', 'Room Type': 'Single'},
            {'Room Number': 'E120B', 'Room Type': 'Single'},
            {'Room Number': 'E123B', 'Room Type': 'Single'},
            {'Room Number': 'E123A', 'Room Type': 'Single'},
            {'Room Number': 'E121B', 'Room Type': 'Double'},
            {'Room Number': 'E121A', 'Room Type': 'Double'},
            {'Room Number': 'E119B', 'Room Type': 'Double'},
            {'Room Number': 'E119A', 'Room Type': 'Double'},
            {'Room Number': 'E117B', 'Room Type': 'Double'},
            {'Room Number': 'E117A', 'Room Type': 'Double'},
            {'Room Number': 'E115B', 'Room Type': 'Double'},
            {'Room Number': 'E115A', 'Room Type': 'Double'},
            {'Room Number': 'E113B', 'Room Type': 'Double'},
            {'Room Number': 'E113A', 'Room Type': 'Double'},
            {'Room Number': 'E111B', 'Room Type': 'Single'},
            {'Room Number': 'E111A', 'Room Type': 'Single'},
            {'Room Number': 'E114A', 'Room Type': 'Double'},
            {'Room Number': 'E114B', 'Room Type': 'Double'},
            {'Room Number': 'E112A', 'Room Type': 'Single'},
            {'Room Number': 'E112B', 'Room Type': 'Single'},
            {'Room Number': 'E101A', 'Room Type': 'Double'},
            {'Room Number': 'E101B', 'Room Type': 'Double'},
            {'Room Number': 'E103A', 'Room Type': 'Double'},
            {'Room Number': 'E103B', 'Room Type': 'Double'},
            {'Room Number': 'E105A', 'Room Type': 'Double'},
            {'Room Number': 'E105B', 'Room Type': 'Double'},
            {'Room Number': 'E107A', 'Room Type': 'Double'},
            {'Room Number': 'E107B', 'Room Type': 'Double'},
            {'Room Number': 'E109A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '017_Max_P_Hoover_Floor_1_pdf_house_0.png',
        'Floor': 1,
        'House Name': 'Hoover',
        'Rooms': [
            {'Room Number': 'E137B', 'Room Type': 'Single'},
            {'Room Number': 'E137A', 'Room Type': 'Single'},
            {'Room Number': 'E135B', 'Room Type': 'Double'},
            {'Room Number': 'E135A', 'Room Type': 'Double'},
            {'Room Number': 'E133B', 'Room Type': 'Double'},
            {'Room Number': 'E133A', 'Room Type': 'Double'},
            {'Room Number': 'E131B', 'Room Type': 'Double'},
            {'Room Number': 'E131A', 'Room Type': 'Double'},
            {'Room Number': 'E129B', 'Room Type': 'Double'},
            {'Room Number': 'E129A', 'Room Type': 'Double'},
            {'Room Number': 'E127B', 'Room Type': 'Single'},
            {'Room Number': 'E128A', 'Room Type': 'Single'},
            {'Room Number': 'E128B', 'Room Type': 'Single'},
            {'Room Number': 'E126A', 'Room Type': 'Double'},
            {'Room Number': 'E126B', 'Room Type': 'Double'},
            {'Room Number': 'E124A', 'Room Type': 'Double'},
            {'Room Number': 'E124B', 'Room Type': 'Double'},
            {'Room Number': 'E122A', 'Room Type': 'Single'},
            {'Room Number': 'E122B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '018_Max_P_Hoover_Floor_2_pdf_house_0.png',
        'Floor': 2,
        'House Name': 'Hoover',
        'Rooms': [
            {'Room Number': 'E237B', 'Room Type': 'Single'},
            {'Room Number': 'E237A', 'Room Type': 'Single'},
            {'Room Number': 'E235B', 'Room Type': 'Double'},
            {'Room Number': 'E235A', 'Room Type': 'Double'},
            {'Room Number': 'E233B', 'Room Type': 'Double'},
            {'Room Number': 'E233A', 'Room Type': 'Double'},
            {'Room Number': 'E227B', 'Room Type': 'Single'},
            {'Room Number': 'E227A', 'Room Type': 'Single'},
            {'Room Number': 'E228A', 'Room Type': 'Single'},
            {'Room Number': 'E228B', 'Room Type': 'Single'},
            {'Room Number': 'E226A', 'Room Type': 'Double'},
            {'Room Number': 'E226B', 'Room Type': 'Double'},
            {'Room Number': 'E224A', 'Room Type': 'Double'},
            {'Room Number': 'E224B', 'Room Type': 'Double'},
            {'Room Number': 'E222A', 'Room Type': 'Single'},
            {'Room Number': 'E222B', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '019_Max_P_May_Floor_2_pdf_house_0.png',
        'Floor': 2,
        'House Name': 'May',
        'Rooms': [
            {'Room Number': 'E220A', 'Room Type': 'Single'},
            {'Room Number': 'E220B', 'Room Type': 'Single'},
            {'Room Number': 'E214A', 'Room Type': 'Double'},
            {'Room Number': 'E214B', 'Room Type': 'Double'},
            {'Room Number': 'E212A', 'Room Type': 'Single'},
            {'Room Number': 'E212B', 'Room Type': 'Single'},
            {'Room Number': 'E223A', 'Room Type': 'Single'},
            {'Room Number': 'E223B', 'Room Type': 'Single'},
            {'Room Number': 'E221B', 'Room Type': 'Double'},
            {'Room Number': 'E221A', 'Room Type': 'Double'},
            {'Room Number': 'E219B', 'Room Type': 'Double'},
            {'Room Number': 'E219A', 'Room Type': 'Double'},
            {'Room Number': 'E217B', 'Room Type': 'Double'},
            {'Room Number': 'E217A', 'Room Type': 'Double'},
            {'Room Number': 'E215B', 'Room Type': 'Double'},
            {'Room Number': 'E215A', 'Room Type': 'Double'},
            {'Room Number': 'E213B', 'Room Type': 'Double'},
            {'Room Number': 'E213A', 'Room Type': 'Double'},
            {'Room Number': 'E211B', 'Room Type': 'Single'},
            {'Room Number': 'E211A', 'Room Type': 'Single'},
            {'Room Number': 'E201A', 'Room Type': 'Double'},
            {'Room Number': 'E201B', 'Room Type': 'Double'},
            {'Room Number': 'E203A', 'Room Type': 'Double'},
            {'Room Number': 'E203B', 'Room Type': 'Double'},
            {'Room Number': 'E205A', 'Room Type': 'Double'},
            {'Room Number': 'E205B', 'Room Type': 'Double'},
            {'Room Number': 'E207A', 'Room Type': 'Double'},
            {'Room Number': 'E207B', 'Room Type': 'Double'},
            {'Room Number': 'E209A', 'Room Type': 'Single'},
            {'Room Number': 'E209B', 'Room Type': 'Single'},
            {'Room Number': 'E210A', 'Room Type': 'Single'},
        ]
    },
    {
        'Image': '020_Max_P_Hoover_Floor_4_pdf_house_0.png',
        'Floor': 4,
        'House Name': 'Hoover',
        'Rooms': [
            {'Room Number': 'E427B', 'Room Type': 'Single'},
            {'Room Number': 'E427A', 'Room Type': 'Single'},
            {'Room Number': 'E428A', 'Room Type': 'Single'},
            {'Room Number': 'E428B', 'Room Type': 'Single'},
            {'Room Number': 'E426A', 'Room Type': 'Double'},
            {'Room Number': 'E426B', 'Room Type': 'Double'},
            {'Room Number': 'E424A', 'Room Type': 'Double'},
            {'Room Number': 'E424B', 'Room Type': 'Double'},
            {'Room Number': 'E422A', 'Room Type': 'Single'},
            {'Room Number': 'E422B', 'Room Type': 'Single'},
        ]
    }
]

def generate_csv():
    output_path = "data/floorplans/Max Palevsky/colored_rooms.csv"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Room Number', 'Floor', 'Building Name', 'House Name', 'Room Type', 'Original Image'])
        
        for image_data in rooms_data:
            floor = image_data['Floor']
            house = image_data['House Name']
            image_name = image_data['Image']
            
            for room in image_data['Rooms']:
                writer.writerow([
                    room['Room Number'],
                    floor,
                    "Max Palevsky",
                    house,
                    room['Room Type'],
                    image_name
                ])
                
    print(f"Successfully wrote {output_path}")

if __name__ == "__main__":
    generate_csv()
